# Generated by Django 5.1.6 on 2025-03-04 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despachos', '0001_initial'),
        ('tipocargos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('escalafon', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(blank=True, max_length=100, null=True)),
                ('convocatoria', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_ultima_novedad', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipocargos.tipocargo')),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='despachos.despacho')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['nombre'],
            },
        ),
    ]
