# Generated by Django 5.1.6 on 2025-03-03 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despachos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='despachos.despacho')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['nombre'],
            },
        ),
    ]
