# Generated by Django 5.1.6 on 2025-03-04 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despachos', '0001_initial'),
        ('tipocargos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('renuncia', 'Renuncia'), ('provisionalidad', 'Provisionalidad'), ('propiedad', 'Propiedad')], max_length=20)),
                ('detalle', models.TextField()),
                ('nombre_despacho', models.CharField(editable=False, max_length=200)),
                ('fecha_acto', models.DateField(verbose_name='Fecha de Acto Administrativo')),
                ('fecha_posesion', models.DateField(verbose_name='Fecha de Posesión')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipocargos.tipocargo')),
                ('codigo_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despachos.despacho')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha_acto'],
            },
        ),
    ]
