# Generated by Django 5.1.6 on 2025-03-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('magistrado', 'Magistrado'), ('secretario', 'Secretario'), ('auxiliar', 'Auxiliar'), ('administrador', 'Administrador')], default='auxiliar', max_length=20),
        ),
    ]
