# Generated by Django 5.1.6 on 2025-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiccion', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('circuito', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['jurisdiccion', 'distrito', 'circuito'],
            },
        ),
    ]
