# Generated by Django 5.1.6 on 2025-03-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('jurisdiccion', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('circuito', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['codigo'],
            },
        ),
    ]
